version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        command: npm run test && npm run bundlesize
        background: true

      - run: yarn start:app

      - run: yarn cypress
