name: API Extrator

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-depenedencies

      - name: Build
        run: pnpm build:esm

      - name: API Extractor
        run: pnpm api-extractor:ci
