name: API Extrator

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:esm

      - name: API Extractor
        run: pnpm api-extractor:ci
