name: E2E Test (manual)

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Cypress run
        run: yarn start:app & sleep 60 && yarn cypress:parallel
