name: Unit Test / Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run install
        run: npm install

      - name: Run test
        run: npm run lint && npm run test

      - name: Lint
          run: |
            npm run lint:types
            npm run lint

      - name: Test
        run: npm test
        env:
          CI: true
          
      - name: Build
          run: npm run build
