name: Unit Test / Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run install
        run: |
          npm install
          npm run lint && npm run test
          npm run lint:types
          npm run lint
          npm run build
