name: Cypress

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: app
        run: npm run start:app
      - name: Slesleepep
        run: sleep 30
      - npm: cypress
        run: npm run cypress:parallel
