name: Cypress

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Cypress
        run: npm run cy:parallel
        with:
          start: npm run start:app
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
