name: Unit Test / Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Node environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x

      - name: Cache node modules
        id: node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - if: steps.node-modules.outputs.cache-hit != 'true'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Package Check
        run: |
          npm run check:package
      - name: Lint
        run: |
          npm run lint:types
          npm run lint
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Build
        run: npm run build
